//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesasAbiertasProducto
    {
        public string IdMesaAbiertaProducto { get; set; }
        public string IdMesaAbierta { get; set; }
        public string IdProducto { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> TasaIva { get; set; }
        public Nullable<double> PrecioConIva { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Costo { get; set; }
        public string EnviarComanda { get; set; }
        public string Departamento { get; set; }
        public string Grupo { get; set; }
        public string Comentario { get; set; }
        public string Mesonero { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public string NumeroComanda { get; set; }
        public Nullable<bool> Alerta { get; set; }
        public Nullable<double> TotalBase { get; set; }
    
        public virtual MesasAbierta MesasAbierta { get; set; }
    }
}
