//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesasCerrada
    {
        public MesasCerrada()
        {
            this.MesasCerradasProductos = new HashSet<MesasCerradasProducto>();
        }
    
        public string IdMesaCerrada { get; set; }
        public string CodigoMesa { get; set; }
        public string Salon { get; set; }
        public string Mesonero { get; set; }
        public Nullable<int> Personas { get; set; }
        public Nullable<System.DateTime> Apertura { get; set; }
        public Nullable<System.DateTime> Cierre { get; set; }
        public Nullable<double> MontoGravable { get; set; }
        public Nullable<double> MontoExento { get; set; }
        public Nullable<double> MontoIva { get; set; }
        public Nullable<double> MontoTotal { get; set; }
        public Nullable<double> MontoServicio { get; set; }
        public string Numero { get; set; }
        public Nullable<int> NumeroImpresiones { get; set; }
        public string Factura { get; set; }
        public string CedulaRif { get; set; }
        public string RazonSocial { get; set; }
        public string NumeroZ { get; set; }
        public Nullable<bool> TieneCorte { get; set; }
        public string IdFactura { get; set; }
    
        public virtual ICollection<MesasCerradasProducto> MesasCerradasProductos { get; set; }
    }
}
