//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using HK.BussinessLogic;

    public partial class TercerosMovimiento : Entity
    {
        [MaxLength(40)]
        public string CajaID { get; set; }
        [MaxLength(40)]
        public string DocumentoID { get; set; }
        public Nullable<int> NumeroLote { get; set; }
        public Nullable<DateTime> Fecha { get; set; }
        public Nullable<DateTime> Vence { get; set; }
        [MaxLength(40)]
        [Required(ErrorMessage = "Es requerido el numero")]
        public string Numero { get; set; }
        [MaxLength(40)]
        public string Tipo { get; set; }
        [MaxLength(150)]
        [Required(ErrorMessage = "Es requerido el concepto")]
        public string Concepto { get; set; }
        [MaxLength(150)]
        public string Comentarios { get; set; }
        public Nullable<double> Debito { get; set; }
        public Nullable<double> Credito { get; set; }
        public Nullable<double> Saldo { get; set; }
        public Nullable<double> DescuentoProntoPago { get; set; }
        [MaxLength(40)]
        public string Cuenta { get; set; }
        [MaxLength(150)]
        public string DescripcionCuenta { get; set; }
        public Nullable<bool> ProntoPagoAplicado { get; set; }
        public Nullable<double> PagarHoy { get; set; }
        [MaxLength(40)]
        public string CodigoVendedor { get; set; }
        [MaxLength(150)]
        public string Vendedor { get; set; }
        [MaxLength(40)]
        public string DocumentoAfectado { get; set; }
        [MaxLength(20)]
        public string NumeroCuenta { set; get; }
        [MaxLength(20)]
        public string FormaDePago { set; get; }
        [MaxLength(10)]
        public string CedulaRifBeneficiario { set; get; }
        [MaxLength(150)]
        public string Beneficiario { set; get; }
        public Nullable<double> MontoGravable { set; get; }
        public Nullable<double> MontoIva { set; get; }
        public Nullable<double> MontoExcento { set; get; }
        public Nullable<double> MontoSinDerechoCreditoFiscal { set; get; }
        public Nullable<double> TasaIva { set; get; }
        [MaxLength(40)]
        public string NumeroPago { set; get; }
        [MaxLength(40)]
        public string NumeroControl { set; get; }

        public virtual Tercero Tercero { get; set; }
    }
}
