//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using HK.BussinessLogic;

    public partial class Vale : Entity
    {
        public Vale()
        {
            Fecha = DateTime.Today;
            Concepto = "PRESTAMO PERSONAL";
        }
        public Nullable<DateTime> Fecha { get; set; }
        [MaxLength(40)]
        public string IdCajero { get; set; }
        [MaxLength(150)]
        public string Concepto { get; set; }
        public Nullable<double> Monto { get; set; }
        [MaxLength(150)]
        public string Cajero { get; set; }
        [MaxLength(20)]
        public string Numero { get; set; }
        [MaxLength(10)]
        public string Cedula { get; set; }
        [MaxLength(150)]
        public string Nombre { get; set; }
        public Nullable<int> NumeroLote { get; set; }
    }
}
