//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using HK.BussinessLogic;

    public partial class Vendedor : Entity
    {
        [MaxLength(40)]
        public string Codigo { get; set; }
        [Required(ErrorMessage = "Es requerida la cedula")]
        [MaxLength(10, ErrorMessage = "La cedula Debe tener hasta 10 caracteres")]
        public string CedulaRif { get; set; }
        [Required(ErrorMessage = "Es requerida el Nombre")]
        [MaxLength(150, ErrorMessage = "El Nombre puede tener hasta 100 caracteres")]
        public string Nombre { get; set; }
        [MaxLength(150)]
        public string Direccion { get; set; }
        [MaxLength(40)]
        public string Telefonos { get; set; }
        [MaxLength(40)]
        public string Email { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<double> ComisionesPendientes { get; set; }
        public Nullable<double> PorcentajeComision { get; set; }
    }
}
