//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using HK.BussinessLogic;

    public partial class Evento : Entity
    {
        public Nullable<DateTime> Fecha { get; set; }
        [MaxLength(100)]
        public string Tipo { get; set; }
        [MaxLength(100)]
        public string Modulo { get; set; }
        [MaxLength(100)]
        public string Estacion { get; set; }
        [MaxLength(100)]
        public string Usuario { get; set; }
        [MaxLength(200)]
        public string Descripcion { get; set; }
        public Nullable<DateTime> Dia { get; set; }
        [MaxLength(100)]
        public string Mesa { get; set; }
        [MaxLength(100)]
        public string Mesonero { get; set; }
        [MaxLength(150)]
        public string Comentario { get; set; }
        public Nullable<int> NumeroImpresiones { get; set; }
        public Nullable<DateTime> Hora { get; set; }
        public Nullable<bool> TieneEventos { get; set; }
    }
}
