//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using HK.BussinessLogic;

    public partial class MaestroDeCuenta : Entity
    {
        [Required(ErrorMessage = "La codigo del producto es obligatorio")]
        [MaxLength(20, ErrorMessage = "La codigo Debe tener hasta 6 caracteres")]
        public string Codigo { get; set; }
        [Required(ErrorMessage = "La descripcion es obligatoria")]
        [MaxLength(80, ErrorMessage = "La descripcion Debe tener hasta 6 caracteres")]
        public string Descripcion { get; set; }
    }
}
