//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using HK.BussinessLogic;

    public partial class Parametro : Entity
    {
        [MaxLength(10)]
        public string EmpresaRif { get; set; }
        [MaxLength(150)]
        public string Empresa { get; set; }
        [MaxLength(150)]
        public string EmpresaDireccion { get; set; }
        [MaxLength(40)]
        public string EmpresaTelefonos { get; set; }
        public Nullable<double> TasaIva { get; set; }
        [MaxLength(40)]
        public string TipoIva { get; set; }
        [MaxLength(40)]
        public string Ciudad { get; set; }
        [MaxLength(100)]
        public string Licencia { get; set; }
        public Nullable<double> TasaIvaB { get; set; }
        public Nullable<double> TasaIvaC { get; set; }
        public Nullable<double> PorcentajeRetencion { get; set; }
        [MaxLength(40)]
        public string PeriodoFiscal { get; set; }
        [MaxLength(100)]
        public string NotaCorteCuenta1 { get; set; }
        [MaxLength(100)]
        public string NotaCorteCuenta2 { get; set; }
        [MaxLength(100)]
        public string NotaCorteCuenta3 { get; set; }
        [MaxLength(100)]
        public string NotaCorteCuenta4 { get; set; }
        [MaxLength(100)]
        public string NotaPieFactura { get; set; }
        [MaxLength(100)]
        public string NotaPieFactura2 { get; set; }
        [MaxLength(100)]
        public string NotaPieFactura3 { get; set; }
        [MaxLength(100)]
        public string NotaPieCotizacion { get; set; }
        [MaxLength(100)]
        public string NotaPieCotizacion2 { get; set; }
        [MaxLength(100)]
        public string NotaPieCotizacion3 { get; set; }
        [MaxLength(100)]
        public string NotaPieNotaEntrega { get; set; }
        [MaxLength(100)]
        public string NotaPieNotaEntrega2 { get; set; }
        [MaxLength(100)]
        public string NotaPieNotaEntrega3 { get; set; }

        public Nullable<double> Utilidad { get; set; }
        public Nullable<double> Utilidad2 { get; set; }
        public Nullable<double> Utilidad3 { get; set; }
        public Nullable<double> Utilidad4 { get; set; }
        [MaxLength(20)]
        public string CalculoPrecios { get; set; }
        public Nullable<int> CantidadPrecios { get; set; }
        [MaxLength(20)]
        public string TipoCliente { get; set; }
    }
}
