//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using HK.BussinessLogic;

    public partial class Grupo : Entity
    {
        public Grupo()
        {
        }
        [Required(ErrorMessage = "Es requerido el Grupo")]
        [MaxLength(20)]
        public string GrupoDescripcion { get; set; }
        [MaxLength(400)]
        public string Contornos { get; set; }
        [MaxLength(400)]
        public string Comentarios { get; set; }
        //public string[] getContornos() {
        //   // return this.Contornos.Split(",");
        //}
        //public string[] getComentarios()
        //{
        //  //  return this.Comentarios.Split( ",");
        //}
    }
}
