//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using HK.BussinessLogic;

    public partial class Mesa : Entity
    {
        public Mesa()
        {
            CobraServicio = true;
        }
        [Required(ErrorMessage = "Es requerido el Codigo")]
        [MaxLength(20)]
        public string Codigo { get; set; }
        [Required(ErrorMessage = "Es requerida la Ubicacion")]
        [MaxLength(40)]
        public string Ubicacion { get; set; }
        public Nullable<bool> CobraServicio { get; set; }
        // Auxiliares
        [NotMapped]
        public string Numero { set; get; }
        [NotMapped]
        public DateTime? Apertura { set; get; }
        [NotMapped]
        public int? NumeroImpresiones { set; get; }
        [NotMapped]
        public DateTime? UltimaImpresion { set; get; }
        [NotMapped]
        public string RazonSocial { set; get; }
        [NotMapped]
        public string Mesonero { set; get; }
        [NotMapped]
        public double? Monto { set; get; }
        [NotMapped]
        public Nullable<bool> Bloqueada { get; set; }
        [NotMapped]
        public Nullable<bool> TieneBebidas { get; set; }
        [NotMapped]
        public Nullable<bool> TieneComidas { get; set; }
        [NotMapped]
        public Nullable<bool> TieneEventos { get; set; }
    }
}
