//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using HK.BussinessLogic;

    public partial class Mesonero : Entity
    {
        public Mesonero() 
        {
             
        }
        [Required(ErrorMessage = "Es requerida la cedula o rif")]
        [MaxLength(10, ErrorMessage = "La cedula o rif debe tener 10 caracteres")]
        public string Cedula { get; set; }
        [Required(ErrorMessage = "Es requerido el nombre")]
        [MaxLength(100, ErrorMessage = "El Nombre debe tener hasta 150 caracteres")]
        public string Nombre { get; set; }
        [MaxLength(20)]
        public string Codigo { get; set; }
        public Nullable<double> Puntos { get; set; }
        public Nullable<bool> Activo { get; set; }
        [MaxLength(150)]
        public string Direccion { get; set; }
        [MaxLength(40)]
        public string Telefonos { get; set; }
        [MaxLength(40)]
        public string Cargo { get; set; }

        public Nullable<bool> PuedeDarCreditos { get; set; }
        public Nullable<bool> PuedeCambiarMesa { get; set; }
        public Nullable<bool> AnularPlatos { get; set; }
        public Nullable<bool> PuedeRegistrarPago { get; set; }
        public Nullable<bool> PuedeDarConsumoInterno { get; set; }
        public Nullable<bool> PuedePedirCorteDeCuenta { get; set; }
        public Nullable<bool> PuedeSepararCuentas { get; set; }
        public Nullable<bool> PuedeDividirCuentas { get; set; }
        public Nullable<bool> PuedeCambiarPrecios { get; set; }
        public Nullable<bool> PuedeLiberarMesa { get; set; }
        public Nullable<bool> PuedeAnularMesa { get; set; }
    }
}
