//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using HK.BussinessLogic;

    public partial class LibroVenta : Entity
    {
        double? mTasaIvaContribuyentes;
        double? mTasaIvaNoContribuyentes;
        public LibroVenta()
        {

        }
        [MaxLength(40)]
        public string FacturaID { get; set; }
        public Nullable<DateTime> Fecha { get; set; }
        [MaxLength(20)]
        public string Factura { get; set; }
        [MaxLength(20)]
        public string NotaCredito { get; set; }
        [MaxLength(20)]
        public string NotaDebito { get; set; }
        [MaxLength(6)]
        public string NumeroZ { get; set; }
        [MaxLength(20)]
        public string MaquinaFiscal { get; set; }
        [MaxLength(150)]
        public string RazonSocial { get; set; }
        [MaxLength(10)]
        public string CedulaRif { get; set; }
        [MaxLength(20)]
        public string Comprobante { get; set; }
        [MaxLength(20)]
        public string FacturaAfectada { get; set; }
        [MaxLength(20)]
        public string TipoOperacion { get; set; }
        public Nullable<double> MontoTotal { get; set; }
        public Nullable<double> MontoExento { get; set; }
        public Nullable<double> IvaRetenido { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<double> MontoGravableContribuyentes { get; set; }
        public Nullable<double> MontoGravableNoContribuyentes { get; set; }
        public Nullable<double> MontoIvaContribuyentes { get; set; }
        public Nullable<double> MontoIvaNoContribuyentes { get; set; }
        public double? TasaIvaContribuyentes
        {
            set
            { mTasaIvaContribuyentes = value; }
            get
            {
                if (mTasaIvaContribuyentes == null)
                {
                    mTasaIvaContribuyentes = OK.SystemParameters.TasaIva;
                }
                return mTasaIvaContribuyentes;
            }
        }
        public double? TasaIvaNoContribuyentes
        {
            set
            { mTasaIvaNoContribuyentes = value; }
            get
            {
                if (mTasaIvaNoContribuyentes == null)
                {
                    mTasaIvaNoContribuyentes = OK.SystemParameters.TasaIva;
                }
                return mTasaIvaNoContribuyentes;
            }
        }
        [NotMapped]
        public string Inicio { get; set; }
        [NotMapped]
        public string Final { get; set; }
        public void Calcular()
        {
            MontoIvaContribuyentes = MontoGravableContribuyentes.GetValueOrDefault() * TasaIvaContribuyentes.GetValueOrDefault() / 100;
            MontoIvaNoContribuyentes = MontoGravableNoContribuyentes.GetValueOrDefault() * TasaIvaNoContribuyentes.GetValueOrDefault() / 100;
            MontoTotal = MontoExento.GetValueOrDefault() +
                         MontoGravableContribuyentes.GetValueOrDefault() +
                         MontoGravableNoContribuyentes.GetValueOrDefault() +
                         MontoIvaContribuyentes.GetValueOrDefault() +
                         MontoIvaNoContribuyentes.GetValueOrDefault();
        }
    }
}
