//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using HK.BussinessLogic;

    public class Banco : Entity
    {
        public Banco()
        {
            this.BancosMovimientos = new HashSet<BancosMovimiento>();
        }
        [Required]
        [MaxLength(20)]
        public string Cuenta { get; set; }
        [Required]
        [MaxLength(150)]
        public string Descripcion { get; set; }
        [MaxLength(100)]
        public string Agencia { get; set; }
        [MaxLength(100)]
        public string Telefonos { get; set; }
        [MaxLength(100)]
        public string Email { get; set; }
        [MaxLength(150)]
        public string Contacto { get; set; }
        public Nullable<DateTime> FechaApertura { get; set; }
        public Nullable<double> MontoInicial { get; set; }
        public Nullable<double> Saldo { get; set; }
        public Nullable<double> ComisionTarjetasCredito { get; set; }
        public Nullable<double> ComisionTarjetaDebito { get; set; }
        public Nullable<double> RetencionISLR { get; set; }
        public Nullable<bool> PoseePuntoDeVenta { get; set; }
        public Nullable<double> ComsionTodoTicket { get; set; }
        /// <summary>
        /// Logs
        /// </summary>
        public Nullable<DateTime> UltimaEdicion { get; set; }
        [MaxLength(40)]
        public string UsuarioID { get; set; }

        public virtual ICollection<BancosMovimiento> BancosMovimientos { get; set; }
    }
}
