//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class DatosEntities : DbContext
    {
        public DatosEntities(string connectionString)
            : base(connectionString)
        {
            Database.SetInitializer<DatosEntities>(null);
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Configurations.Add(new AgendaConfiguration());
            modelBuilder.Configurations.Add(new AuxiliarBancoConfiguration());
            modelBuilder.Configurations.Add(new BancoConfiguration());
            modelBuilder.Configurations.Add(new BancosDepositosDetalleConfiguration());
            modelBuilder.Configurations.Add(new BancosMovimientoConfiguration());
            modelBuilder.Configurations.Add(new CajaCierreConfiguration());
            modelBuilder.Configurations.Add(new CajasConfiguration());
            modelBuilder.Configurations.Add(new CajasChicaConfiguration());
            modelBuilder.Configurations.Add(new ClientesConfiguration());
            modelBuilder.Configurations.Add(new ClientesMovimientosConfiguration());
            modelBuilder.Configurations.Add(new ComprasConfiguration());
            modelBuilder.Configurations.Add(new ComprasProductosConfiguration());
            modelBuilder.Configurations.Add(new ContadoresConfiguration());
            modelBuilder.Configurations.Add(new CotizacionesConfiguration());
            modelBuilder.Configurations.Add(new CotizacionesProductosConfiguration());
            modelBuilder.Configurations.Add(new DepartamentosConfiguration());
            modelBuilder.Configurations.Add(new DepositosConfiguration());
            modelBuilder.Configurations.Add(new DepositosExistenciasConfiguration());
            modelBuilder.Configurations.Add(new EventosConfiguration());
            modelBuilder.Configurations.Add(new FacturasConfiguration());
            modelBuilder.Configurations.Add(new FacturasProductosConfiguration());
            modelBuilder.Configurations.Add(new LibroVentasConfiguration());
            modelBuilder.Configurations.Add(new LibroInventariosConfiguration());
            modelBuilder.Configurations.Add(new MaestroDeCuentasConfiguration());
            modelBuilder.Configurations.Add(new MesasConfiguration());
            modelBuilder.Configurations.Add(new MesasAbiertasConfiguration());
            modelBuilder.Configurations.Add(new MesasAbiertasProductosConfiguration());
            modelBuilder.Configurations.Add(new MesasAbiertasProductosAnuladosConfiguration());
            modelBuilder.Configurations.Add(new MesasCerradasConfiguration());
            modelBuilder.Configurations.Add(new MesasCerradasProductosConfiguration());
            modelBuilder.Configurations.Add(new MesonerosConfiguration());
            modelBuilder.Configurations.Add(new NotasEntregasConfiguration());
            modelBuilder.Configurations.Add(new NotasEntregasProductosConfiguration());
            modelBuilder.Configurations.Add(new ParametrosConfiguration());
            modelBuilder.Configurations.Add(new PedidosConfiguration());
            modelBuilder.Configurations.Add(new PedidosProductosConfiguration());
            modelBuilder.Configurations.Add(new ProductosConfiguration());
            modelBuilder.Configurations.Add(new ProductosCompuestosConfiguration());
            modelBuilder.Configurations.Add(new ProductosInventariosConfiguration());
            modelBuilder.Configurations.Add(new ProductosMovimientosConfiguration());
            modelBuilder.Configurations.Add(new ProveedoresConfiguration());
            modelBuilder.Configurations.Add(new ProveedoresMovimientosConfiguration());
            modelBuilder.Configurations.Add(new RetencionesConfiguration());
            modelBuilder.Configurations.Add(new RetencionesISLRsConfiguration());
            modelBuilder.Configurations.Add(new SugerenciasConfiguration());
            modelBuilder.Configurations.Add(new TrasladosConfiguration());
            modelBuilder.Configurations.Add(new TrasladosProductosConfiguration());
            modelBuilder.Configurations.Add(new VendedoresConfiguration());
            modelBuilder.Configurations.Add(new VendedoresMovimientosConfiguration());
            modelBuilder.Configurations.Add(new ValesConfiguration());
            modelBuilder.Configurations.Add(new UsuariosConfiguration());
            base.OnModelCreating(modelBuilder);
        }
        public DbSet<Agenda> Agendas { get; set; }
        public DbSet<AuxiliarBanco> AuxiliarBancos { get; set; }
        public DbSet<Banco> Bancos { get; set; }
        public DbSet<BancosDepositosDetalle> BancosDepositosDetalles { get; set; }
        public DbSet<BancosMovimiento> BancosMovimientos { get; set; }
        public DbSet<CajaCierre> CajaCierres { get; set; }
        public DbSet<Caja> Cajas { get; set; }
        public DbSet<CajasChica> CajasChicas { get; set; }
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<ClientesMovimiento> ClientesMovimientos { get; set; }
        public DbSet<Compra> Compras { get; set; }
        public DbSet<ComprasProducto> ComprasProductos { get; set; }
        public DbSet<Contadore> Contadores { get; set; }
        public DbSet<Cotizacion> Cotizaciones { get; set; }
        public DbSet<CotizacionesProducto> CotizacionesProductos { get; set; }
        public DbSet<Departamento> Departamentos { get; set; }
        public DbSet<Deposito> Depositos { get; set; }
        public DbSet<DepositosExistencia> DepositosExistencias { get; set; }
        public DbSet<Evento> Eventos { get; set; }
        public DbSet<Factura> Facturas { get; set; }
        public DbSet<FacturasProducto> FacturasProductos { get; set; }
        public DbSet<LibroCompra> LibroCompras { get; set; }
        public DbSet<LibroInventario> LibroInventarios { get; set; }
        public DbSet<LibroVenta> LibroVentas { get; set; }
        public DbSet<MaestroDeCuenta> MaestroDeCuentas { get; set; }
        public DbSet<Mesa> Mesas { get; set; }
        public DbSet<MesasAbierta> MesasAbiertas { get; set; }
        public DbSet<MesasAbiertasProducto> MesasAbiertasProductos { get; set; }
        public DbSet<MesasAbiertasProductosAnulado> MesasAbiertasProductosAnulados { get; set; }
        public DbSet<MesasCerrada> MesasCerradas { get; set; }
        public DbSet<MesasCerradasProducto> MesasCerradasProductos { get; set; }
        public DbSet<Mesonero> Mesoneros { get; set; }
        public DbSet<NotasEntrega> NotasEntregas { get; set; }
        public DbSet<NotasEntregasProducto> NotasEntregasProductos { get; set; }
        public DbSet<Parametro> Parametros { get; set; }
        public DbSet<Pedido> Pedidos { get; set; }
        public DbSet<PedidosProducto> PedidosProductos { get; set; }
        public DbSet<Producto> Productos { get; set; }
        public DbSet<ProductosCompuesto> ProductosCompuestos { get; set; }
        public DbSet<ProductosInventario> ProductosInventarios { get; set; }
        public DbSet<ProductosMovimiento> ProductosMovimientos { get; set; }
        public DbSet<Proveedor> Proveedores { get; set; }
        public DbSet<ProveedoresMovimiento> ProveedoresMovimientos { get; set; }
        public DbSet<Retencion> Retenciones { get; set; }
        public DbSet<RetencionesISLR> RetencionesISLRs { get; set; }
        public DbSet<Sugerencia> Sugerencias { get; set; }
        public DbSet<Traslado> Traslados { get; set; }
        public DbSet<TrasladosProducto> TrasladosProductos { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<Vale> Vales { get; set; }
        public DbSet<Vendedor> Vendedores { get; set; }
        public DbSet<VendedoresMovimiento> VendedoresMovimientos { get; set; }

    }
}
